config/routes.rb
Rails.application.routes.draw do
  
  root 'tweets#home'

  post 'tweets/send_tweet'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def home
  	@tweet = ''
  end

  def send_tweet
  	@tweet = Tweet.new(tweet_params)
  	@tweet = @tweet.content
  	send_tweet = SendTweet.new(@tweet)
   	send_tweet.connexion
  	send_tweet.send_tweet
    flash[:notice] = "Votre tweet a été envoyé!"
    redirect_to root_path
  	
  end

  private #on ne récupère de la view que les données qui nous intéressent (anonyme_user et content) - placé ici dans le script par convention
    def tweet_params
      params.permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterBis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/home.html.erb
<h1>Créer un nouveau tweet</h1>
<p> </p>
<%= form_tag (tweets_send_tweet_path) do %>

 
    
  <%= label_tag 'text', 'Tweet :' %>
  <%= text_field_tag 'content' %>
  <%= submit_tag 'Envoyer!' %>
<% end %>

app/views/tweets/send.html.erb
<h1>Créer un nouveau tweet</h1>
<p> </p>
<%= form_tag (tweets_send_path) do %>

 
    
  <%= label_tag 'text', 'Tweet :' %>
  <%= text_field_tag 'content' %>
  <%= submit_tag 'Créer un nouveau ragot' %>
<% end %>